[gov]
title = "gov"
url = "https://www.gov.pl/web/baza-wiedzy/cyberbezpieczny-samorzad"
entrySelector = ".art-prev > ul li"
titleSelector = "div >.title"
linkSelector = "a"
contentSelector = ".intro"

[funfacts]
title = "Wikipedia — did you know?"
url = "https://en.wikipedia.org/wiki/Main_Page"
entrySelector = "#mp-dyk > ul li"
titleSelector = "b"
linkSelector = "b a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
