[govCyberbezpiecznySamorzad]
title = "Cyberbezpieczny samorzad"
url = "https://www.gov.pl/web/baza-wiedzy/cyberbezpieczny-samorzad"
entrySelector = ".art-prev > ul li"
titleSelector = "div >.title"
linkSelector = "a"
contentSelector = ".intro"

[govCyberhigena]
title = "Cyberhigiena - dla kazdego"
url = "https://www.gov.pl/web/baza-wiedzy/cyberbezpieczenstwo"
entrySelector = ".art-prev > ul li"
titleSelector = "div >.title"
linkSelector = "a"
contentSelector = ".intro"

[govDlaProfesjonalistow]
title = "Dla profesjonalistow"
url = "https://www.gov.pl/web/baza-wiedzy/dla-profesjonalistow"
entrySelector = ".art-prev > ul li"
titleSelector = "div >.title"
linkSelector = "a"
contentSelector = ".intro"

[informatykZakladowy]
title = "Informatyk zakladowu"
url = "https://informatykzakladowy.pl/"
entrySelector = "#site-content > article"
titleSelector = "h2"
linkSelector = "h2 a"
contentSelector = ".entry-content"
